export const countryCodes: { [key: string]: string } = {
    "US": "United States",
    "CA": "Canada",
    "PT": "Portugal",
    "ZW": "Zimbabwe",
    "ES": "Spain",
    "FR": "France",
    "DE": "Germany",
    "AT": "Austria",
    "IT": "Italy",
    "GR": "Greece",
    "RU": "Russia",
    "UA": "Ukraine",
    "TR": "Turkey",
    "EG": "Egypt",
    "MA": "Morocco",
    "DZ": "Algeria",
    "TN": "Tunisia",
    "LY": "Libya",
    "IL": "",
    "JO": "Jordan",
    "LB": "Lebanon",
    "IQ": "Iraq",
    "IR": "Iran",
    "SA": "Saudi Arabia",
    "YE": "Yemen",
    "OM": "Oman",
    "AE": "United Arab Emirates",
    "QA": "Qatar",
    "KW": "Kuwait",
    "BH": "Bahrain",
    "PK": "Pakistan",
    "AF": "Afghanistan",
    "IN": "India",
    "NP": "Nepal",
    "BD": "Bangladesh",
    "LK": "Sri Lanka",
    "MM": "Myanmar",
    "TH": "Thailand",
    "VN": "Vietnam",
    "LA": "Laos",
    "KH": "Cambodia",
    "MY": "Malaysia",
    "SG": "Singapore",
    "ID": "Indonesia",
    "PH": "Philippines",
    "CN": "China",
    "MN": "Mongolia",
    "KP": "North Korea",
    "KR": "South Korea",
    "JP": "Japan",
    "TW": "Taiwan",
    "AU": "Australia",
    "NZ": "New Zealand",
    "PG": "Papua New Guinea",
    "SB": "Solomon Islands",
    "VU": "Vanuatu",
    "FJ": "Fiji",
    "TO": "Tonga",
    "WS": "Samoa",
    "KI": "Kiribati",
    "MH": "Marshall Islands",
    "LT": "Lithuania",
    "BE": "Belgium",
    "GH": "Ghana",
    "BR": "Brazil",
    "RS": "Serbia",
    "EE": "Estonia",
    "PL": "Poland",
    "AD": "Andorra",
    "FI": "Finland",
    "LV": "Latvia",
    "NO": "Norway",
    "SI": "Slovenia",
    "RO": "Romania",
    "KZ": "Kazakhstan",
    "BW": "Botswana",
    "MK": "Macedonia",
    "HR": "Croatia",
    "KG": "Kyrgyzstan",
    "BY": "Belarus",
    "XK": "Kosovo",
    "DK": "Denmark",
    "HU": "Hungary",
    "BA": "Bosnia and Herzegovina",
    "SE": "Sweden",
    "NL": "Netherlands",
    "CH": "Switzerland",
    "IE": "Ireland",
    "NG": "Nigeria",
    "MX": "Mexico",
    "CZ": "Czech Republic",
    "CI": "Ivory Coast",
    "AW": "Aruba",
    "TZ": "Tanzania",
    "AR": "Argentina",
    "KE": "Kenya",
    "SK": "Slovakia",
    "MG": "Madagascar",
    "BF": "Burkina Faso",
    "UZ": "Uzbekistan",
    "NA": "Namibia",
    "LU": "Luxembourg",
    "GB": "United Kingdom",
    "PY": "Paraguay",
    "CY": "Cyprus",
    "TG": "Togo",
    "CL": "Chile",
    "GP": "Guadeloupe",
    "ZA": "South Africa",
    "GY": "Guyana",
    "CO": "Colombia",
    "BN": "Brunei",
    "UG": "Uganda",
    "PR": "Puerto Rico",
    "MS": "Montserrat",
};