name: Download JSON Daily

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression schedules the workflow to run daily at midnight UTC
  workflow_dispatch:  # Allows the workflow to be run manually

jobs:
  download-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Download JSON
        run: |
          node -e "
          const fetch = require('node-fetch');
          const fs = require('fs');
          fetch('https://play.fiba3x3.com/api/v2/search/events?name=&input=&when=future&distance=1000&pageNum=1')
            .then(response => response.json())
            .then(data => {
              fs.writeFileSync('daily_tournament_fetch.json', JSON.stringify(data, null, 2));
            })
          .catch(error => console.error('Error fetching JSON:', error));
          "

      - name: Commit and push JSON file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add daily_tournament_fetch.json
          git commit -m 'Daily update of JSON data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
